version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seplag-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    networks:
      - seplag-network
    depends_on:
      - db
      - minio

  db:
    image: postgres:latest
    container_name: seplag-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - seplag-network

  minio:
    image: minio/minio
    container_name: seplag-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - seplag-network

  nginx:
    image: nginx:alpine
    container_name: seplag-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - seplag-network
    depends_on:
      - app

networks:
  seplag-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data: